/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Courts: () => import('#controllers/courts_controller'),
  GuestReservations: () => import('#controllers/guest_reservations_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Reservations: () => import('#controllers/reservations_controller'),
  Settings: () => import('#controllers/settings_controller'),
  Stats: () => import('#controllers/stats_controller'),
  UserAuditLogs: () => import('#controllers/user_audit_logs_controller'),
  Users: () => import('#controllers/users_controller'),
}
