/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CourtPriceRangeSchema extends BaseModel {
  static $columns = ['courtId', 'createdAt', 'endHour', 'id', 'isPeakHour', 'price120Min', 'price60Min', 'price90Min', 'pricePerHour', 'startHour', 'updatedAt'] as const
  $columns = CourtPriceRangeSchema.$columns
  @column()
  declare courtId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endHour: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPeakHour: boolean
  @column()
  declare price120Min: string | null
  @column()
  declare price60Min: string | null
  @column()
  declare price90Min: string | null
  @column()
  declare pricePerHour: string
  @column()
  declare startHour: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CourtSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isActive', 'name', 'parentCourtId', 'pricePerHour', 'type', 'updatedAt'] as const
  $columns = CourtSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare parentCourtId: number | null
  @column()
  declare pricePerHour: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReservationAuditLogSchema extends BaseModel {
  static $columns = ['createdAt', 'field', 'id', 'newValue', 'oldValue', 'performedBy', 'reservationId'] as const
  $columns = ReservationAuditLogSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare field: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare newValue: string | null
  @column()
  declare oldValue: string | null
  @column()
  declare performedBy: number | null
  @column()
  declare reservationId: number
}

export class ReservationHiddenDateSchema extends BaseModel {
  static $columns = ['createdAt', 'hiddenDate', 'id', 'reservationId', 'updatedAt'] as const
  $columns = ReservationHiddenDateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare hiddenDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reservationId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReservationSchema extends BaseModel {
  static $columns = ['cancelledAt', 'cancelledBy', 'classType', 'confirmedAt', 'confirmedBy', 'consecutiveGames', 'consecutiveGamesSnapshot', 'contactPhone', 'courtId', 'createdAt', 'customPrice', 'customerId', 'depositFixedAmount', 'depositPaid', 'depositPaidAt', 'depositPaidBy', 'depositPercentage', 'depositReceipt', 'discountPercentage', 'endTime', 'hiddenFrom', 'hiddenUntil', 'id', 'isRecurring', 'lastIncrementedAt', 'notes', 'startTime', 'status', 'totalPaid', 'totalPaidAt', 'totalPaidBy', 'totalPaidCount', 'totalPrice', 'totalReceipt', 'updatedAt', 'userId'] as const
  $columns = ReservationSchema.$columns
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare cancelledBy: number | null
  @column()
  declare classType: string | null
  @column.dateTime()
  declare confirmedAt: DateTime | null
  @column()
  declare confirmedBy: number | null
  @column()
  declare consecutiveGames: number
  @column()
  declare consecutiveGamesSnapshot: number | null
  @column()
  declare contactPhone: string | null
  @column()
  declare courtId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customPrice: string | null
  @column()
  declare customerId: number | null
  @column()
  declare depositFixedAmount: string | null
  @column()
  declare depositPaid: boolean
  @column.dateTime()
  declare depositPaidAt: DateTime | null
  @column()
  declare depositPaidBy: number | null
  @column()
  declare depositPercentage: string | null
  @column()
  declare depositReceipt: string | null
  @column()
  declare discountPercentage: string
  @column.dateTime()
  declare endTime: DateTime
  @column.date()
  declare hiddenFrom: DateTime | null
  @column.date()
  declare hiddenUntil: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isRecurring: boolean
  @column.dateTime()
  declare lastIncrementedAt: DateTime | null
  @column()
  declare notes: string | null
  @column.dateTime()
  declare startTime: DateTime
  @column()
  declare status: string
  @column()
  declare totalPaid: boolean
  @column.dateTime()
  declare totalPaidAt: DateTime | null
  @column()
  declare totalPaidBy: number | null
  @column()
  declare totalPaidCount: number
  @column()
  declare totalPrice: string
  @column()
  declare totalReceipt: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class SettingSchema extends BaseModel {
  static $columns = ['key', 'value'] as const
  $columns = SettingSchema.$columns
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare value: string | null
}

export class UserAuditLogSchema extends BaseModel {
  static $columns = ['createdAt', 'field', 'id', 'newValue', 'oldValue', 'performedBy', 'targetUserId'] as const
  $columns = UserAuditLogSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare field: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare newValue: string | null
  @column()
  declare oldValue: string | null
  @column()
  declare performedBy: number | null
  @column()
  declare targetUserId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'hasLoggedIn', 'id', 'padelCategory', 'password', 'phone', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column()
  declare hasLoggedIn: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare padelCategory: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
