/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CourtPriceRangeSchema extends BaseModel {
  static $columns = ['courtId', 'createdAt', 'endHour', 'id', 'isPeakHour', 'pricePerHour', 'startHour', 'updatedAt'] as const
  $columns = CourtPriceRangeSchema.$columns
  @column()
  declare courtId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endHour: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPeakHour: boolean
  @column()
  declare pricePerHour: string
  @column()
  declare startHour: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CourtSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isActive', 'name', 'parentCourtId', 'pricePerHour', 'type', 'updatedAt'] as const
  $columns = CourtSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare parentCourtId: number | null
  @column()
  declare pricePerHour: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReservationSchema extends BaseModel {
  static $columns = ['contactPhone', 'courtId', 'createdAt', 'customerId', 'depositPaid', 'depositPercentage', 'depositReceipt', 'endTime', 'hiddenUntil', 'id', 'isRecurring', 'notes', 'startTime', 'status', 'totalPaid', 'totalPrice', 'totalReceipt', 'updatedAt', 'userId'] as const
  $columns = ReservationSchema.$columns
  @column()
  declare contactPhone: string | null
  @column()
  declare courtId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: number | null
  @column()
  declare depositPaid: boolean
  @column()
  declare depositPercentage: string | null
  @column()
  declare depositReceipt: string | null
  @column.dateTime()
  declare endTime: DateTime
  @column.date()
  declare hiddenUntil: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isRecurring: boolean
  @column()
  declare notes: string | null
  @column.dateTime()
  declare startTime: DateTime
  @column()
  declare status: string
  @column()
  declare totalPaid: boolean
  @column()
  declare totalPrice: string
  @column()
  declare totalReceipt: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class SettingSchema extends BaseModel {
  static $columns = ['key', 'value'] as const
  $columns = SettingSchema.$columns
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare value: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'hasLoggedIn', 'id', 'password', 'phone', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column()
  declare hasLoggedIn: boolean
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
