/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CashBundleSchema extends BaseModel {
  static $columns = [
    'amount',
    'cancelledAt',
    'cancelledBy',
    'cancelledInCashSessionId',
    'cashSessionId',
    'createdAt',
    'createdBy',
    'id',
    'notes',
    'status',
    'updatedAt',
  ] as const
  $columns = CashBundleSchema.$columns
  @column()
  declare amount: string
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare cancelledBy: number | null
  @column()
  declare cancelledInCashSessionId: number | null
  @column()
  declare cashSessionId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CashSessionSchema extends BaseModel {
  static $columns = [
    'bundlesEfectivo',
    'businessDate',
    'closedAt',
    'closedBy',
    'countedEfectivo',
    'createdAt',
    'expectedCloseAt',
    'id',
    'inEfectivo',
    'inPostnet',
    'inTransferencia',
    'movementsCount',
    'notes',
    'openMarker',
    'openedAt',
    'openedBy',
    'openingEfectivo',
    'outEfectivo',
    'outPostnet',
    'outTransferencia',
    'shiftEndMinute',
    'shiftName',
    'shiftStartMinute',
    'updatedAt',
  ] as const
  $columns = CashSessionSchema.$columns
  @column()
  declare bundlesEfectivo: string
  @column.date()
  declare businessDate: DateTime
  @column.dateTime()
  declare closedAt: DateTime | null
  @column()
  declare closedBy: number | null
  @column()
  declare countedEfectivo: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expectedCloseAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inEfectivo: string
  @column()
  declare inPostnet: string
  @column()
  declare inTransferencia: string
  @column()
  declare movementsCount: number
  @column()
  declare notes: string | null
  @column()
  declare openMarker: boolean | null
  @column.dateTime()
  declare openedAt: DateTime
  @column()
  declare openedBy: number
  @column()
  declare openingEfectivo: string
  @column()
  declare outEfectivo: string
  @column()
  declare outPostnet: string
  @column()
  declare outTransferencia: string
  @column()
  declare shiftEndMinute: number
  @column()
  declare shiftName: string
  @column()
  declare shiftStartMinute: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CommerceAuditLogSchema extends BaseModel {
  static $columns = [
    'action',
    'createdAt',
    'entityId',
    'entityLabel',
    'entityType',
    'field',
    'id',
    'newValue',
    'oldValue',
    'performedBy',
  ] as const
  $columns = CommerceAuditLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: number
  @column()
  declare entityLabel: string
  @column()
  declare entityType: string
  @column()
  declare field: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare newValue: string | null
  @column()
  declare oldValue: string | null
  @column()
  declare performedBy: number | null
}

export class CourtPriceHistorySchema extends BaseModel {
  static $columns = [
    'courtId',
    'createdAt',
    'effectiveFrom',
    'endHour',
    'id',
    'isPeakHour',
    'price120Min',
    'price60Min',
    'price90Min',
    'pricePerHour',
    'startHour',
  ] as const
  $columns = CourtPriceHistorySchema.$columns
  @column()
  declare courtId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare effectiveFrom: DateTime
  @column()
  declare endHour: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPeakHour: boolean
  @column()
  declare price120Min: string | null
  @column()
  declare price60Min: string | null
  @column()
  declare price90Min: string | null
  @column()
  declare pricePerHour: string
  @column()
  declare startHour: string
}

export class CourtPriceRangeSchema extends BaseModel {
  static $columns = [
    'courtId',
    'createdAt',
    'endHour',
    'id',
    'isPeakHour',
    'price120Min',
    'price60Min',
    'price90Min',
    'pricePerHour',
    'startHour',
    'updatedAt',
  ] as const
  $columns = CourtPriceRangeSchema.$columns
  @column()
  declare courtId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endHour: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPeakHour: boolean
  @column()
  declare price120Min: string | null
  @column()
  declare price60Min: string | null
  @column()
  declare price90Min: string | null
  @column()
  declare pricePerHour: string
  @column()
  declare startHour: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CourtSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'depositPercentage',
    'description',
    'id',
    'isActive',
    'name',
    'parentCourtId',
    'pricePerHour',
    'type',
    'updatedAt',
  ] as const
  $columns = CourtSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare depositPercentage: string | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare parentCourtId: number | null
  @column()
  declare pricePerHour: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExpenseCategorySchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = ExpenseCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExpenseSchema extends BaseModel {
  static $columns = [
    'amount',
    'cancelledAt',
    'cancelledBy',
    'cancelledInCashSessionId',
    'cashSessionId',
    'categoryId',
    'createdAt',
    'createdBy',
    'description',
    'efectivo',
    'expenseDate',
    'id',
    'notes',
    'postnet',
    'status',
    'supplier',
    'transferencia',
    'updatedAt',
  ] as const
  $columns = ExpenseSchema.$columns
  @column()
  declare amount: string
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare cancelledBy: number | null
  @column()
  declare cancelledInCashSessionId: number | null
  @column()
  declare cashSessionId: number | null
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare description: string
  @column()
  declare efectivo: string
  @column.date()
  declare expenseDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare postnet: string
  @column()
  declare status: string
  @column()
  declare supplier: string | null
  @column()
  declare transferencia: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ModuleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt', 'visibleName'] as const
  $columns = ModuleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare visibleName: string
}

export class ProductCategorySchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = ProductCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductSchema extends BaseModel {
  static $columns = [
    'categoryId',
    'cost',
    'createdAt',
    'deletedAt',
    'id',
    'isActive',
    'minStock',
    'name',
    'price',
    'sku',
    'stock',
    'trackStock',
    'updatedAt',
  ] as const
  $columns = ProductSchema.$columns
  @column()
  declare categoryId: number | null
  @column()
  declare cost: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare minStock: number
  @column()
  declare name: string
  @column()
  declare price: string
  @column()
  declare sku: string | null
  @column()
  declare stock: number
  @column()
  declare trackStock: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProfessorPriceHistorySchema extends BaseModel {
  static $columns = [
    'createdAt',
    'effectiveFrom',
    'id',
    'priceGroup',
    'priceIndividual',
    'priceIndividualWeekend',
  ] as const
  $columns = ProfessorPriceHistorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare effectiveFrom: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare priceGroup: string
  @column()
  declare priceIndividual: string
  @column()
  declare priceIndividualWeekend: string
}

export class ReservationAuditLogSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'field',
    'id',
    'newValue',
    'oldValue',
    'performedBy',
    'reservationId',
  ] as const
  $columns = ReservationAuditLogSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare field: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare newValue: string | null
  @column()
  declare oldValue: string | null
  @column()
  declare performedBy: number | null
  @column()
  declare reservationId: number
}

export class ReservationHiddenDateSchema extends BaseModel {
  static $columns = ['createdAt', 'hiddenDate', 'id', 'reservationId', 'updatedAt'] as const
  $columns = ReservationHiddenDateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare hiddenDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reservationId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReservationPaymentSchema extends BaseModel {
  static $columns = [
    'cashSessionId',
    'createdAt',
    'efectivo',
    'expectedAmount',
    'id',
    'occurrenceDate',
    'paidBy',
    'postnet',
    'receipt',
    'reservationId',
    'revertedAt',
    'revertedBy',
    'revertedInCashSessionId',
    'total',
    'transferencia',
    'type',
  ] as const
  $columns = ReservationPaymentSchema.$columns
  @column()
  declare cashSessionId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare efectivo: string
  @column()
  declare expectedAmount: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare occurrenceDate: DateTime | null
  @column()
  declare paidBy: number
  @column()
  declare postnet: string
  @column()
  declare receipt: string | null
  @column()
  declare reservationId: number
  @column.dateTime()
  declare revertedAt: DateTime | null
  @column()
  declare revertedBy: number | null
  @column()
  declare revertedInCashSessionId: number | null
  @column()
  declare total: string
  @column()
  declare transferencia: string
  @column()
  declare type: string
}

export class ReservationSchema extends BaseModel {
  static $columns = [
    'cancelledAt',
    'cancelledBy',
    'classType',
    'confirmedAt',
    'confirmedBy',
    'consecutiveGames',
    'consecutiveGamesSnapshot',
    'contactPhone',
    'courtId',
    'createdAt',
    'customPrice',
    'customerId',
    'depositFixedAmount',
    'depositPaid',
    'depositPaidAt',
    'depositPaidBy',
    'depositPercentage',
    'depositReceipt',
    'discountPercentage',
    'endTime',
    'hiddenFrom',
    'hiddenUntil',
    'id',
    'isRecurring',
    'lastIncrementedAt',
    'notes',
    'startTime',
    'status',
    'totalPaid',
    'totalPaidAt',
    'totalPaidBy',
    'totalPaidCount',
    'totalPrice',
    'totalReceipt',
    'updatedAt',
    'userId',
  ] as const
  $columns = ReservationSchema.$columns
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare cancelledBy: number | null
  @column()
  declare classType: string | null
  @column.dateTime()
  declare confirmedAt: DateTime | null
  @column()
  declare confirmedBy: number | null
  @column()
  declare consecutiveGames: number
  @column()
  declare consecutiveGamesSnapshot: number | null
  @column()
  declare contactPhone: string | null
  @column()
  declare courtId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customPrice: string | null
  @column()
  declare customerId: number | null
  @column()
  declare depositFixedAmount: string | null
  @column()
  declare depositPaid: boolean
  @column.dateTime()
  declare depositPaidAt: DateTime | null
  @column()
  declare depositPaidBy: number | null
  @column()
  declare depositPercentage: string | null
  @column()
  declare depositReceipt: string | null
  @column()
  declare discountPercentage: string
  @column.dateTime()
  declare endTime: DateTime
  @column.date()
  declare hiddenFrom: DateTime | null
  @column.date()
  declare hiddenUntil: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isRecurring: boolean
  @column.dateTime()
  declare lastIncrementedAt: DateTime | null
  @column()
  declare notes: string | null
  @column.dateTime()
  declare startTime: DateTime
  @column()
  declare status: string
  @column()
  declare totalPaid: boolean
  @column.dateTime()
  declare totalPaidAt: DateTime | null
  @column()
  declare totalPaidBy: number | null
  @column()
  declare totalPaidCount: number
  @column()
  declare totalPrice: string
  @column()
  declare totalReceipt: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class RolePermissionSchema extends BaseModel {
  static $columns = [
    'create',
    'createdAt',
    'deletedAt',
    'erase',
    'id',
    'module',
    'roleId',
    'update',
    'updatedAt',
    'view',
  ] as const
  $columns = RolePermissionSchema.$columns
  @column()
  declare create: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare erase: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare module: string
  @column()
  declare roleId: number
  @column()
  declare update: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare view: boolean
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SaleItemSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'productId',
    'productName',
    'quantity',
    'saleId',
    'subtotal',
    'unitCost',
    'unitPrice',
  ] as const
  $columns = SaleItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare productId: number | null
  @column()
  declare productName: string
  @column()
  declare quantity: number
  @column()
  declare saleId: number
  @column()
  declare subtotal: string
  @column()
  declare unitCost: string
  @column()
  declare unitPrice: string
}

export class SaleSchema extends BaseModel {
  static $columns = [
    'cancelledAt',
    'cancelledBy',
    'cancelledInCashSessionId',
    'cashSessionId',
    'createdAt',
    'customerId',
    'efectivo',
    'id',
    'notes',
    'postnet',
    'status',
    'total',
    'transferencia',
    'updatedAt',
    'userId',
  ] as const
  $columns = SaleSchema.$columns
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare cancelledBy: number | null
  @column()
  declare cancelledInCashSessionId: number | null
  @column()
  declare cashSessionId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: number | null
  @column()
  declare efectivo: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare postnet: string
  @column()
  declare status: string
  @column()
  declare total: string
  @column()
  declare transferencia: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class SettingSchema extends BaseModel {
  static $columns = ['key', 'value'] as const
  $columns = SettingSchema.$columns
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare value: string | null
}

export class StockMovementSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'performedBy',
    'productId',
    'quantity',
    'reason',
    'saleId',
    'stockAfter',
    'stockBefore',
    'type',
  ] as const
  $columns = StockMovementSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare performedBy: number
  @column()
  declare productId: number
  @column()
  declare quantity: number
  @column()
  declare reason: string | null
  @column()
  declare saleId: number | null
  @column()
  declare stockAfter: number
  @column()
  declare stockBefore: number
  @column()
  declare type: string
}

export class UserAuditLogSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'field',
    'id',
    'newValue',
    'oldValue',
    'performedBy',
    'targetUserId',
  ] as const
  $columns = UserAuditLogSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare field: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare newValue: string | null
  @column()
  declare oldValue: string | null
  @column()
  declare performedBy: number | null
  @column()
  declare targetUserId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'fullName',
    'hasLoggedIn',
    'id',
    'isSuperUser',
    'padelCategory',
    'password',
    'phone',
    'role',
    'roleId',
    'status',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column()
  declare hasLoggedIn: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSuperUser: boolean
  @column()
  declare padelCategory: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare role: string
  @column()
  declare roleId: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UsersPermissionSchema extends BaseModel {
  static $columns = [
    'create',
    'createdAt',
    'deletedAt',
    'erase',
    'id',
    'module',
    'update',
    'updatedAt',
    'userId',
    'view',
  ] as const
  $columns = UsersPermissionSchema.$columns
  @column()
  declare create: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare erase: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare module: string
  @column()
  declare update: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare view: boolean
}
