/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'new_account.store': {
    methods: ["POST"],
    pattern: '/api/v1/auth/signup',
    tokens: [{"old":"/api/v1/auth/signup","type":0,"val":"api","end":""},{"old":"/api/v1/auth/signup","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/signup","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['new_account.store']['types'],
  },
  'access_tokens.store': {
    methods: ["POST"],
    pattern: '/api/v1/auth/login',
    tokens: [{"old":"/api/v1/auth/login","type":0,"val":"api","end":""},{"old":"/api/v1/auth/login","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/login","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['access_tokens.store']['types'],
  },
  'settings.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/settings',
    tokens: [{"old":"/api/v1/settings","type":0,"val":"api","end":""},{"old":"/api/v1/settings","type":0,"val":"v1","end":""},{"old":"/api/v1/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['settings.show']['types'],
  },
  'courts.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/courts',
    tokens: [{"old":"/api/v1/courts","type":0,"val":"api","end":""},{"old":"/api/v1/courts","type":0,"val":"v1","end":""},{"old":"/api/v1/courts","type":0,"val":"courts","end":""}],
    types: placeholder as Registry['courts.index']['types'],
  },
  'reservations.availability': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/courts/availability',
    tokens: [{"old":"/api/v1/courts/availability","type":0,"val":"api","end":""},{"old":"/api/v1/courts/availability","type":0,"val":"v1","end":""},{"old":"/api/v1/courts/availability","type":0,"val":"courts","end":""},{"old":"/api/v1/courts/availability","type":0,"val":"availability","end":""}],
    types: placeholder as Registry['reservations.availability']['types'],
  },
  'courts.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/courts/:id',
    tokens: [{"old":"/api/v1/courts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/courts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/courts/:id","type":0,"val":"courts","end":""},{"old":"/api/v1/courts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['courts.show']['types'],
  },
  'guest_reservations.store': {
    methods: ["POST"],
    pattern: '/api/v1/guest/reservations',
    tokens: [{"old":"/api/v1/guest/reservations","type":0,"val":"api","end":""},{"old":"/api/v1/guest/reservations","type":0,"val":"v1","end":""},{"old":"/api/v1/guest/reservations","type":0,"val":"guest","end":""},{"old":"/api/v1/guest/reservations","type":0,"val":"reservations","end":""}],
    types: placeholder as Registry['guest_reservations.store']['types'],
  },
  'profile.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/account/profile',
    tokens: [{"old":"/api/v1/account/profile","type":0,"val":"api","end":""},{"old":"/api/v1/account/profile","type":0,"val":"v1","end":""},{"old":"/api/v1/account/profile","type":0,"val":"account","end":""},{"old":"/api/v1/account/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['profile.show']['types'],
  },
  'access_tokens.destroy': {
    methods: ["POST"],
    pattern: '/api/v1/account/logout',
    tokens: [{"old":"/api/v1/account/logout","type":0,"val":"api","end":""},{"old":"/api/v1/account/logout","type":0,"val":"v1","end":""},{"old":"/api/v1/account/logout","type":0,"val":"account","end":""},{"old":"/api/v1/account/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['access_tokens.destroy']['types'],
  },
  'complete_profile.store': {
    methods: ["PUT"],
    pattern: '/api/v1/account/complete-profile',
    tokens: [{"old":"/api/v1/account/complete-profile","type":0,"val":"api","end":""},{"old":"/api/v1/account/complete-profile","type":0,"val":"v1","end":""},{"old":"/api/v1/account/complete-profile","type":0,"val":"account","end":""},{"old":"/api/v1/account/complete-profile","type":0,"val":"complete-profile","end":""}],
    types: placeholder as Registry['complete_profile.store']['types'],
  },
  'courts.store': {
    methods: ["POST"],
    pattern: '/api/v1/courts',
    tokens: [{"old":"/api/v1/courts","type":0,"val":"api","end":""},{"old":"/api/v1/courts","type":0,"val":"v1","end":""},{"old":"/api/v1/courts","type":0,"val":"courts","end":""}],
    types: placeholder as Registry['courts.store']['types'],
  },
  'courts.update': {
    methods: ["PUT"],
    pattern: '/api/v1/courts/:id',
    tokens: [{"old":"/api/v1/courts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/courts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/courts/:id","type":0,"val":"courts","end":""},{"old":"/api/v1/courts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['courts.update']['types'],
  },
  'courts.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/courts/:id',
    tokens: [{"old":"/api/v1/courts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/courts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/courts/:id","type":0,"val":"courts","end":""},{"old":"/api/v1/courts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['courts.destroy']['types'],
  },
  'courts.toggle_active': {
    methods: ["PATCH"],
    pattern: '/api/v1/courts/:id/toggle',
    tokens: [{"old":"/api/v1/courts/:id/toggle","type":0,"val":"api","end":""},{"old":"/api/v1/courts/:id/toggle","type":0,"val":"v1","end":""},{"old":"/api/v1/courts/:id/toggle","type":0,"val":"courts","end":""},{"old":"/api/v1/courts/:id/toggle","type":1,"val":"id","end":""},{"old":"/api/v1/courts/:id/toggle","type":0,"val":"toggle","end":""}],
    types: placeholder as Registry['courts.toggle_active']['types'],
  },
  'courts.update_price_ranges': {
    methods: ["PUT"],
    pattern: '/api/v1/courts/:id/price-ranges',
    tokens: [{"old":"/api/v1/courts/:id/price-ranges","type":0,"val":"api","end":""},{"old":"/api/v1/courts/:id/price-ranges","type":0,"val":"v1","end":""},{"old":"/api/v1/courts/:id/price-ranges","type":0,"val":"courts","end":""},{"old":"/api/v1/courts/:id/price-ranges","type":1,"val":"id","end":""},{"old":"/api/v1/courts/:id/price-ranges","type":0,"val":"price-ranges","end":""}],
    types: placeholder as Registry['courts.update_price_ranges']['types'],
  },
  'reservations.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/reservations',
    tokens: [{"old":"/api/v1/reservations","type":0,"val":"api","end":""},{"old":"/api/v1/reservations","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations","type":0,"val":"reservations","end":""}],
    types: placeholder as Registry['reservations.index']['types'],
  },
  'reservations.next': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/reservations/next',
    tokens: [{"old":"/api/v1/reservations/next","type":0,"val":"api","end":""},{"old":"/api/v1/reservations/next","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations/next","type":0,"val":"reservations","end":""},{"old":"/api/v1/reservations/next","type":0,"val":"next","end":""}],
    types: placeholder as Registry['reservations.next']['types'],
  },
  'reservations.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/reservations/:id',
    tokens: [{"old":"/api/v1/reservations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/reservations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations/:id","type":0,"val":"reservations","end":""},{"old":"/api/v1/reservations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['reservations.show']['types'],
  },
  'reservations.store': {
    methods: ["POST"],
    pattern: '/api/v1/reservations',
    tokens: [{"old":"/api/v1/reservations","type":0,"val":"api","end":""},{"old":"/api/v1/reservations","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations","type":0,"val":"reservations","end":""}],
    types: placeholder as Registry['reservations.store']['types'],
  },
  'reservations.update': {
    methods: ["PUT"],
    pattern: '/api/v1/reservations/:id',
    tokens: [{"old":"/api/v1/reservations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/reservations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations/:id","type":0,"val":"reservations","end":""},{"old":"/api/v1/reservations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['reservations.update']['types'],
  },
  'reservations.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/reservations/:id',
    tokens: [{"old":"/api/v1/reservations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/reservations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations/:id","type":0,"val":"reservations","end":""},{"old":"/api/v1/reservations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['reservations.destroy']['types'],
  },
  'reservations.update_notes': {
    methods: ["PATCH"],
    pattern: '/api/v1/reservations/:id/notes',
    tokens: [{"old":"/api/v1/reservations/:id/notes","type":0,"val":"api","end":""},{"old":"/api/v1/reservations/:id/notes","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations/:id/notes","type":0,"val":"reservations","end":""},{"old":"/api/v1/reservations/:id/notes","type":1,"val":"id","end":""},{"old":"/api/v1/reservations/:id/notes","type":0,"val":"notes","end":""}],
    types: placeholder as Registry['reservations.update_notes']['types'],
  },
  'reservations.hide_next': {
    methods: ["PATCH"],
    pattern: '/api/v1/reservations/:id/hide-next',
    tokens: [{"old":"/api/v1/reservations/:id/hide-next","type":0,"val":"api","end":""},{"old":"/api/v1/reservations/:id/hide-next","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations/:id/hide-next","type":0,"val":"reservations","end":""},{"old":"/api/v1/reservations/:id/hide-next","type":1,"val":"id","end":""},{"old":"/api/v1/reservations/:id/hide-next","type":0,"val":"hide-next","end":""}],
    types: placeholder as Registry['reservations.hide_next']['types'],
  },
  'reservations.update_promo': {
    methods: ["PATCH"],
    pattern: '/api/v1/reservations/:id/promo',
    tokens: [{"old":"/api/v1/reservations/:id/promo","type":0,"val":"api","end":""},{"old":"/api/v1/reservations/:id/promo","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations/:id/promo","type":0,"val":"reservations","end":""},{"old":"/api/v1/reservations/:id/promo","type":1,"val":"id","end":""},{"old":"/api/v1/reservations/:id/promo","type":0,"val":"promo","end":""}],
    types: placeholder as Registry['reservations.update_promo']['types'],
  },
  'reservations.show_next': {
    methods: ["PATCH"],
    pattern: '/api/v1/reservations/:id/show-next',
    tokens: [{"old":"/api/v1/reservations/:id/show-next","type":0,"val":"api","end":""},{"old":"/api/v1/reservations/:id/show-next","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations/:id/show-next","type":0,"val":"reservations","end":""},{"old":"/api/v1/reservations/:id/show-next","type":1,"val":"id","end":""},{"old":"/api/v1/reservations/:id/show-next","type":0,"val":"show-next","end":""}],
    types: placeholder as Registry['reservations.show_next']['types'],
  },
  'reservations.pay_deposit': {
    methods: ["PATCH"],
    pattern: '/api/v1/reservations/:id/pay-deposit',
    tokens: [{"old":"/api/v1/reservations/:id/pay-deposit","type":0,"val":"api","end":""},{"old":"/api/v1/reservations/:id/pay-deposit","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations/:id/pay-deposit","type":0,"val":"reservations","end":""},{"old":"/api/v1/reservations/:id/pay-deposit","type":1,"val":"id","end":""},{"old":"/api/v1/reservations/:id/pay-deposit","type":0,"val":"pay-deposit","end":""}],
    types: placeholder as Registry['reservations.pay_deposit']['types'],
  },
  'reservations.pay_total': {
    methods: ["PATCH"],
    pattern: '/api/v1/reservations/:id/pay-total',
    tokens: [{"old":"/api/v1/reservations/:id/pay-total","type":0,"val":"api","end":""},{"old":"/api/v1/reservations/:id/pay-total","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations/:id/pay-total","type":0,"val":"reservations","end":""},{"old":"/api/v1/reservations/:id/pay-total","type":1,"val":"id","end":""},{"old":"/api/v1/reservations/:id/pay-total","type":0,"val":"pay-total","end":""}],
    types: placeholder as Registry['reservations.pay_total']['types'],
  },
  'reservations.settle_debt': {
    methods: ["PATCH"],
    pattern: '/api/v1/reservations/:id/settle-debt',
    tokens: [{"old":"/api/v1/reservations/:id/settle-debt","type":0,"val":"api","end":""},{"old":"/api/v1/reservations/:id/settle-debt","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations/:id/settle-debt","type":0,"val":"reservations","end":""},{"old":"/api/v1/reservations/:id/settle-debt","type":1,"val":"id","end":""},{"old":"/api/v1/reservations/:id/settle-debt","type":0,"val":"settle-debt","end":""}],
    types: placeholder as Registry['reservations.settle_debt']['types'],
  },
  'reservations.audit_logs': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/reservations/:id/audit',
    tokens: [{"old":"/api/v1/reservations/:id/audit","type":0,"val":"api","end":""},{"old":"/api/v1/reservations/:id/audit","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations/:id/audit","type":0,"val":"reservations","end":""},{"old":"/api/v1/reservations/:id/audit","type":1,"val":"id","end":""},{"old":"/api/v1/reservations/:id/audit","type":0,"val":"audit","end":""}],
    types: placeholder as Registry['reservations.audit_logs']['types'],
  },
  'reservations.revert': {
    methods: ["PATCH"],
    pattern: '/api/v1/reservations/:id/revert',
    tokens: [{"old":"/api/v1/reservations/:id/revert","type":0,"val":"api","end":""},{"old":"/api/v1/reservations/:id/revert","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations/:id/revert","type":0,"val":"reservations","end":""},{"old":"/api/v1/reservations/:id/revert","type":1,"val":"id","end":""},{"old":"/api/v1/reservations/:id/revert","type":0,"val":"revert","end":""}],
    types: placeholder as Registry['reservations.revert']['types'],
  },
  'reservations.revert_payment': {
    methods: ["DELETE"],
    pattern: '/api/v1/reservations/:id/payments/:paymentId',
    tokens: [{"old":"/api/v1/reservations/:id/payments/:paymentId","type":0,"val":"api","end":""},{"old":"/api/v1/reservations/:id/payments/:paymentId","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations/:id/payments/:paymentId","type":0,"val":"reservations","end":""},{"old":"/api/v1/reservations/:id/payments/:paymentId","type":1,"val":"id","end":""},{"old":"/api/v1/reservations/:id/payments/:paymentId","type":0,"val":"payments","end":""},{"old":"/api/v1/reservations/:id/payments/:paymentId","type":1,"val":"paymentId","end":""}],
    types: placeholder as Registry['reservations.revert_payment']['types'],
  },
  'reservations.revert_all_payments': {
    methods: ["DELETE"],
    pattern: '/api/v1/reservations/:id/payments',
    tokens: [{"old":"/api/v1/reservations/:id/payments","type":0,"val":"api","end":""},{"old":"/api/v1/reservations/:id/payments","type":0,"val":"v1","end":""},{"old":"/api/v1/reservations/:id/payments","type":0,"val":"reservations","end":""},{"old":"/api/v1/reservations/:id/payments","type":1,"val":"id","end":""},{"old":"/api/v1/reservations/:id/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['reservations.revert_all_payments']['types'],
  },
  'product_categories.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/product-categories',
    tokens: [{"old":"/api/v1/product-categories","type":0,"val":"api","end":""},{"old":"/api/v1/product-categories","type":0,"val":"v1","end":""},{"old":"/api/v1/product-categories","type":0,"val":"product-categories","end":""}],
    types: placeholder as Registry['product_categories.index']['types'],
  },
  'product_categories.store': {
    methods: ["POST"],
    pattern: '/api/v1/product-categories',
    tokens: [{"old":"/api/v1/product-categories","type":0,"val":"api","end":""},{"old":"/api/v1/product-categories","type":0,"val":"v1","end":""},{"old":"/api/v1/product-categories","type":0,"val":"product-categories","end":""}],
    types: placeholder as Registry['product_categories.store']['types'],
  },
  'product_categories.update': {
    methods: ["PUT"],
    pattern: '/api/v1/product-categories/:id',
    tokens: [{"old":"/api/v1/product-categories/:id","type":0,"val":"api","end":""},{"old":"/api/v1/product-categories/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/product-categories/:id","type":0,"val":"product-categories","end":""},{"old":"/api/v1/product-categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['product_categories.update']['types'],
  },
  'product_categories.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/product-categories/:id',
    tokens: [{"old":"/api/v1/product-categories/:id","type":0,"val":"api","end":""},{"old":"/api/v1/product-categories/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/product-categories/:id","type":0,"val":"product-categories","end":""},{"old":"/api/v1/product-categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['product_categories.destroy']['types'],
  },
  'products.catalog': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/products/catalog',
    tokens: [{"old":"/api/v1/products/catalog","type":0,"val":"api","end":""},{"old":"/api/v1/products/catalog","type":0,"val":"v1","end":""},{"old":"/api/v1/products/catalog","type":0,"val":"products","end":""},{"old":"/api/v1/products/catalog","type":0,"val":"catalog","end":""}],
    types: placeholder as Registry['products.catalog']['types'],
  },
  'products.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/products',
    tokens: [{"old":"/api/v1/products","type":0,"val":"api","end":""},{"old":"/api/v1/products","type":0,"val":"v1","end":""},{"old":"/api/v1/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['products.index']['types'],
  },
  'products.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/products/:id',
    tokens: [{"old":"/api/v1/products/:id","type":0,"val":"api","end":""},{"old":"/api/v1/products/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/products/:id","type":0,"val":"products","end":""},{"old":"/api/v1/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.show']['types'],
  },
  'products.movements': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/products/:id/movements',
    tokens: [{"old":"/api/v1/products/:id/movements","type":0,"val":"api","end":""},{"old":"/api/v1/products/:id/movements","type":0,"val":"v1","end":""},{"old":"/api/v1/products/:id/movements","type":0,"val":"products","end":""},{"old":"/api/v1/products/:id/movements","type":1,"val":"id","end":""},{"old":"/api/v1/products/:id/movements","type":0,"val":"movements","end":""}],
    types: placeholder as Registry['products.movements']['types'],
  },
  'products.store': {
    methods: ["POST"],
    pattern: '/api/v1/products',
    tokens: [{"old":"/api/v1/products","type":0,"val":"api","end":""},{"old":"/api/v1/products","type":0,"val":"v1","end":""},{"old":"/api/v1/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['products.store']['types'],
  },
  'products.update': {
    methods: ["PUT"],
    pattern: '/api/v1/products/:id',
    tokens: [{"old":"/api/v1/products/:id","type":0,"val":"api","end":""},{"old":"/api/v1/products/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/products/:id","type":0,"val":"products","end":""},{"old":"/api/v1/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.update']['types'],
  },
  'products.toggle_active': {
    methods: ["PATCH"],
    pattern: '/api/v1/products/:id/toggle',
    tokens: [{"old":"/api/v1/products/:id/toggle","type":0,"val":"api","end":""},{"old":"/api/v1/products/:id/toggle","type":0,"val":"v1","end":""},{"old":"/api/v1/products/:id/toggle","type":0,"val":"products","end":""},{"old":"/api/v1/products/:id/toggle","type":1,"val":"id","end":""},{"old":"/api/v1/products/:id/toggle","type":0,"val":"toggle","end":""}],
    types: placeholder as Registry['products.toggle_active']['types'],
  },
  'products.adjust_stock': {
    methods: ["POST"],
    pattern: '/api/v1/products/:id/stock',
    tokens: [{"old":"/api/v1/products/:id/stock","type":0,"val":"api","end":""},{"old":"/api/v1/products/:id/stock","type":0,"val":"v1","end":""},{"old":"/api/v1/products/:id/stock","type":0,"val":"products","end":""},{"old":"/api/v1/products/:id/stock","type":1,"val":"id","end":""},{"old":"/api/v1/products/:id/stock","type":0,"val":"stock","end":""}],
    types: placeholder as Registry['products.adjust_stock']['types'],
  },
  'products.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/products/:id',
    tokens: [{"old":"/api/v1/products/:id","type":0,"val":"api","end":""},{"old":"/api/v1/products/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/products/:id","type":0,"val":"products","end":""},{"old":"/api/v1/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.destroy']['types'],
  },
  'sales.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/sales',
    tokens: [{"old":"/api/v1/sales","type":0,"val":"api","end":""},{"old":"/api/v1/sales","type":0,"val":"v1","end":""},{"old":"/api/v1/sales","type":0,"val":"sales","end":""}],
    types: placeholder as Registry['sales.index']['types'],
  },
  'sales.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/sales/:id',
    tokens: [{"old":"/api/v1/sales/:id","type":0,"val":"api","end":""},{"old":"/api/v1/sales/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/sales/:id","type":0,"val":"sales","end":""},{"old":"/api/v1/sales/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['sales.show']['types'],
  },
  'sales.store': {
    methods: ["POST"],
    pattern: '/api/v1/sales',
    tokens: [{"old":"/api/v1/sales","type":0,"val":"api","end":""},{"old":"/api/v1/sales","type":0,"val":"v1","end":""},{"old":"/api/v1/sales","type":0,"val":"sales","end":""}],
    types: placeholder as Registry['sales.store']['types'],
  },
  'sales.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/sales/:id',
    tokens: [{"old":"/api/v1/sales/:id","type":0,"val":"api","end":""},{"old":"/api/v1/sales/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/sales/:id","type":0,"val":"sales","end":""},{"old":"/api/v1/sales/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['sales.destroy']['types'],
  },
  'expense_categories.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/expense-categories',
    tokens: [{"old":"/api/v1/expense-categories","type":0,"val":"api","end":""},{"old":"/api/v1/expense-categories","type":0,"val":"v1","end":""},{"old":"/api/v1/expense-categories","type":0,"val":"expense-categories","end":""}],
    types: placeholder as Registry['expense_categories.index']['types'],
  },
  'expense_categories.store': {
    methods: ["POST"],
    pattern: '/api/v1/expense-categories',
    tokens: [{"old":"/api/v1/expense-categories","type":0,"val":"api","end":""},{"old":"/api/v1/expense-categories","type":0,"val":"v1","end":""},{"old":"/api/v1/expense-categories","type":0,"val":"expense-categories","end":""}],
    types: placeholder as Registry['expense_categories.store']['types'],
  },
  'expense_categories.update': {
    methods: ["PUT"],
    pattern: '/api/v1/expense-categories/:id',
    tokens: [{"old":"/api/v1/expense-categories/:id","type":0,"val":"api","end":""},{"old":"/api/v1/expense-categories/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/expense-categories/:id","type":0,"val":"expense-categories","end":""},{"old":"/api/v1/expense-categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['expense_categories.update']['types'],
  },
  'expense_categories.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/expense-categories/:id',
    tokens: [{"old":"/api/v1/expense-categories/:id","type":0,"val":"api","end":""},{"old":"/api/v1/expense-categories/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/expense-categories/:id","type":0,"val":"expense-categories","end":""},{"old":"/api/v1/expense-categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['expense_categories.destroy']['types'],
  },
  'expenses.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/expenses',
    tokens: [{"old":"/api/v1/expenses","type":0,"val":"api","end":""},{"old":"/api/v1/expenses","type":0,"val":"v1","end":""},{"old":"/api/v1/expenses","type":0,"val":"expenses","end":""}],
    types: placeholder as Registry['expenses.index']['types'],
  },
  'expenses.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/expenses/:id',
    tokens: [{"old":"/api/v1/expenses/:id","type":0,"val":"api","end":""},{"old":"/api/v1/expenses/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/expenses/:id","type":0,"val":"expenses","end":""},{"old":"/api/v1/expenses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['expenses.show']['types'],
  },
  'expenses.store': {
    methods: ["POST"],
    pattern: '/api/v1/expenses',
    tokens: [{"old":"/api/v1/expenses","type":0,"val":"api","end":""},{"old":"/api/v1/expenses","type":0,"val":"v1","end":""},{"old":"/api/v1/expenses","type":0,"val":"expenses","end":""}],
    types: placeholder as Registry['expenses.store']['types'],
  },
  'expenses.update': {
    methods: ["PUT"],
    pattern: '/api/v1/expenses/:id',
    tokens: [{"old":"/api/v1/expenses/:id","type":0,"val":"api","end":""},{"old":"/api/v1/expenses/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/expenses/:id","type":0,"val":"expenses","end":""},{"old":"/api/v1/expenses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['expenses.update']['types'],
  },
  'expenses.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/expenses/:id',
    tokens: [{"old":"/api/v1/expenses/:id","type":0,"val":"api","end":""},{"old":"/api/v1/expenses/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/expenses/:id","type":0,"val":"expenses","end":""},{"old":"/api/v1/expenses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['expenses.destroy']['types'],
  },
  'users.store': {
    methods: ["POST"],
    pattern: '/api/v1/users',
    tokens: [{"old":"/api/v1/users","type":0,"val":"api","end":""},{"old":"/api/v1/users","type":0,"val":"v1","end":""},{"old":"/api/v1/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['users.store']['types'],
  },
  'users.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/users',
    tokens: [{"old":"/api/v1/users","type":0,"val":"api","end":""},{"old":"/api/v1/users","type":0,"val":"v1","end":""},{"old":"/api/v1/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['users.index']['types'],
  },
  'users.search': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/users/search',
    tokens: [{"old":"/api/v1/users/search","type":0,"val":"api","end":""},{"old":"/api/v1/users/search","type":0,"val":"v1","end":""},{"old":"/api/v1/users/search","type":0,"val":"users","end":""},{"old":"/api/v1/users/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['users.search']['types'],
  },
  'users.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/users/:id',
    tokens: [{"old":"/api/v1/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.show']['types'],
  },
  'users.update': {
    methods: ["PUT"],
    pattern: '/api/v1/users/:id',
    tokens: [{"old":"/api/v1/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.update']['types'],
  },
  'users.reset_login': {
    methods: ["POST"],
    pattern: '/api/v1/users/:id/reset-login',
    tokens: [{"old":"/api/v1/users/:id/reset-login","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id/reset-login","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id/reset-login","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id/reset-login","type":1,"val":"id","end":""},{"old":"/api/v1/users/:id/reset-login","type":0,"val":"reset-login","end":""}],
    types: placeholder as Registry['users.reset_login']['types'],
  },
  'users.toggle_status': {
    methods: ["PATCH"],
    pattern: '/api/v1/users/:id/toggle-status',
    tokens: [{"old":"/api/v1/users/:id/toggle-status","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id/toggle-status","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id/toggle-status","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id/toggle-status","type":1,"val":"id","end":""},{"old":"/api/v1/users/:id/toggle-status","type":0,"val":"toggle-status","end":""}],
    types: placeholder as Registry['users.toggle_status']['types'],
  },
  'user_permissions.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/users/:id/permissions',
    tokens: [{"old":"/api/v1/users/:id/permissions","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id/permissions","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id/permissions","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id/permissions","type":1,"val":"id","end":""},{"old":"/api/v1/users/:id/permissions","type":0,"val":"permissions","end":""}],
    types: placeholder as Registry['user_permissions.show']['types'],
  },
  'user_permissions.update': {
    methods: ["PUT"],
    pattern: '/api/v1/users/:id/permissions',
    tokens: [{"old":"/api/v1/users/:id/permissions","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id/permissions","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id/permissions","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id/permissions","type":1,"val":"id","end":""},{"old":"/api/v1/users/:id/permissions","type":0,"val":"permissions","end":""}],
    types: placeholder as Registry['user_permissions.update']['types'],
  },
  'roles.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/roles',
    tokens: [{"old":"/api/v1/roles","type":0,"val":"api","end":""},{"old":"/api/v1/roles","type":0,"val":"v1","end":""},{"old":"/api/v1/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.index']['types'],
  },
  'roles.modules': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/modules',
    tokens: [{"old":"/api/v1/modules","type":0,"val":"api","end":""},{"old":"/api/v1/modules","type":0,"val":"v1","end":""},{"old":"/api/v1/modules","type":0,"val":"modules","end":""}],
    types: placeholder as Registry['roles.modules']['types'],
  },
  'roles.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/roles/:id',
    tokens: [{"old":"/api/v1/roles/:id","type":0,"val":"api","end":""},{"old":"/api/v1/roles/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/v1/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.show']['types'],
  },
  'roles.store': {
    methods: ["POST"],
    pattern: '/api/v1/roles',
    tokens: [{"old":"/api/v1/roles","type":0,"val":"api","end":""},{"old":"/api/v1/roles","type":0,"val":"v1","end":""},{"old":"/api/v1/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.store']['types'],
  },
  'roles.update': {
    methods: ["PUT"],
    pattern: '/api/v1/roles/:id',
    tokens: [{"old":"/api/v1/roles/:id","type":0,"val":"api","end":""},{"old":"/api/v1/roles/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/v1/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.update']['types'],
  },
  'roles.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/roles/:id',
    tokens: [{"old":"/api/v1/roles/:id","type":0,"val":"api","end":""},{"old":"/api/v1/roles/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/v1/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.destroy']['types'],
  },
  'users.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/users/:id',
    tokens: [{"old":"/api/v1/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.destroy']['types'],
  },
  'stats.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/stats',
    tokens: [{"old":"/api/v1/stats","type":0,"val":"api","end":""},{"old":"/api/v1/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['stats.index']['types'],
  },
  'settings.update': {
    methods: ["PUT"],
    pattern: '/api/v1/settings',
    tokens: [{"old":"/api/v1/settings","type":0,"val":"api","end":""},{"old":"/api/v1/settings","type":0,"val":"v1","end":""},{"old":"/api/v1/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['settings.update']['types'],
  },
  'user_audit_logs.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/audit/users',
    tokens: [{"old":"/api/v1/audit/users","type":0,"val":"api","end":""},{"old":"/api/v1/audit/users","type":0,"val":"v1","end":""},{"old":"/api/v1/audit/users","type":0,"val":"audit","end":""},{"old":"/api/v1/audit/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['user_audit_logs.index']['types'],
  },
  'reservations.audit_logs_all': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/audit/reservations',
    tokens: [{"old":"/api/v1/audit/reservations","type":0,"val":"api","end":""},{"old":"/api/v1/audit/reservations","type":0,"val":"v1","end":""},{"old":"/api/v1/audit/reservations","type":0,"val":"audit","end":""},{"old":"/api/v1/audit/reservations","type":0,"val":"reservations","end":""}],
    types: placeholder as Registry['reservations.audit_logs_all']['types'],
  },
  'commerce_audit_logs.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/audit/commerce',
    tokens: [{"old":"/api/v1/audit/commerce","type":0,"val":"api","end":""},{"old":"/api/v1/audit/commerce","type":0,"val":"v1","end":""},{"old":"/api/v1/audit/commerce","type":0,"val":"audit","end":""},{"old":"/api/v1/audit/commerce","type":0,"val":"commerce","end":""}],
    types: placeholder as Registry['commerce_audit_logs.index']['types'],
  },
  'cash_register.current': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/cash-register/current',
    tokens: [{"old":"/api/v1/cash-register/current","type":0,"val":"api","end":""},{"old":"/api/v1/cash-register/current","type":0,"val":"v1","end":""},{"old":"/api/v1/cash-register/current","type":0,"val":"cash-register","end":""},{"old":"/api/v1/cash-register/current","type":0,"val":"current","end":""}],
    types: placeholder as Registry['cash_register.current']['types'],
  },
  'cash_register.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/cash-register/sessions',
    tokens: [{"old":"/api/v1/cash-register/sessions","type":0,"val":"api","end":""},{"old":"/api/v1/cash-register/sessions","type":0,"val":"v1","end":""},{"old":"/api/v1/cash-register/sessions","type":0,"val":"cash-register","end":""},{"old":"/api/v1/cash-register/sessions","type":0,"val":"sessions","end":""}],
    types: placeholder as Registry['cash_register.index']['types'],
  },
  'cash_register.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/cash-register/sessions/:id',
    tokens: [{"old":"/api/v1/cash-register/sessions/:id","type":0,"val":"api","end":""},{"old":"/api/v1/cash-register/sessions/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/cash-register/sessions/:id","type":0,"val":"cash-register","end":""},{"old":"/api/v1/cash-register/sessions/:id","type":0,"val":"sessions","end":""},{"old":"/api/v1/cash-register/sessions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cash_register.show']['types'],
  },
  'cash_register.open': {
    methods: ["POST"],
    pattern: '/api/v1/cash-register/open',
    tokens: [{"old":"/api/v1/cash-register/open","type":0,"val":"api","end":""},{"old":"/api/v1/cash-register/open","type":0,"val":"v1","end":""},{"old":"/api/v1/cash-register/open","type":0,"val":"cash-register","end":""},{"old":"/api/v1/cash-register/open","type":0,"val":"open","end":""}],
    types: placeholder as Registry['cash_register.open']['types'],
  },
  'cash_register.close': {
    methods: ["POST"],
    pattern: '/api/v1/cash-register/close',
    tokens: [{"old":"/api/v1/cash-register/close","type":0,"val":"api","end":""},{"old":"/api/v1/cash-register/close","type":0,"val":"v1","end":""},{"old":"/api/v1/cash-register/close","type":0,"val":"cash-register","end":""},{"old":"/api/v1/cash-register/close","type":0,"val":"close","end":""}],
    types: placeholder as Registry['cash_register.close']['types'],
  },
  'cash_register.rotate': {
    methods: ["POST"],
    pattern: '/api/v1/cash-register/rotate',
    tokens: [{"old":"/api/v1/cash-register/rotate","type":0,"val":"api","end":""},{"old":"/api/v1/cash-register/rotate","type":0,"val":"v1","end":""},{"old":"/api/v1/cash-register/rotate","type":0,"val":"cash-register","end":""},{"old":"/api/v1/cash-register/rotate","type":0,"val":"rotate","end":""}],
    types: placeholder as Registry['cash_register.rotate']['types'],
  },
  'cash_register.store_bundle': {
    methods: ["POST"],
    pattern: '/api/v1/cash-register/bundles',
    tokens: [{"old":"/api/v1/cash-register/bundles","type":0,"val":"api","end":""},{"old":"/api/v1/cash-register/bundles","type":0,"val":"v1","end":""},{"old":"/api/v1/cash-register/bundles","type":0,"val":"cash-register","end":""},{"old":"/api/v1/cash-register/bundles","type":0,"val":"bundles","end":""}],
    types: placeholder as Registry['cash_register.store_bundle']['types'],
  },
  'cash_register.cancel_bundle': {
    methods: ["POST"],
    pattern: '/api/v1/cash-register/bundles/:id/cancel',
    tokens: [{"old":"/api/v1/cash-register/bundles/:id/cancel","type":0,"val":"api","end":""},{"old":"/api/v1/cash-register/bundles/:id/cancel","type":0,"val":"v1","end":""},{"old":"/api/v1/cash-register/bundles/:id/cancel","type":0,"val":"cash-register","end":""},{"old":"/api/v1/cash-register/bundles/:id/cancel","type":0,"val":"bundles","end":""},{"old":"/api/v1/cash-register/bundles/:id/cancel","type":1,"val":"id","end":""},{"old":"/api/v1/cash-register/bundles/:id/cancel","type":0,"val":"cancel","end":""}],
    types: placeholder as Registry['cash_register.cancel_bundle']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
